/**
    Options for running qunit
*/
module.exports = function(grunt) {
    'use strict';

    // We have to dynamically generate urls because we don't serve actual
    // test files.
    // We delegate url generation to the `qunit_url_mapper` task.
    // We dynamically serve a qunit runner with the `connect:test`
    // task and the urls don't map to actual filenames.
    // EXAMPLE:
    //      test file:
    //          http://localhost:1335/components/bedrock/test/test_class.js
    //      url for test file:
    //          http://localhost:1335/components/bedrock/test/test_class
    return {
        options: {
            // urls are dynamically generated by the `qunit_url_mapper` task
            urls: [],
            timeout: 10000,
        },
        test: {
        }
    };
};
